POST http://localhost:5001/auth/register
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"147258369",
    "nameAccount":"nghia",
    "userName":"nghia",
    "role":"user"
}

###
POST http://localhost:5001/auth/login
Content-Type: application/json

{
    "userName":"nghia",
    "password":"147258369"
}

###
GET http://localhost:5001/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmdoaWEiLCJpYXQiOjE2NzM0MTY4OTksImV4cCI6MTY3MzQyMjg5OX0.HHTiVulWZPAE0Ol9vntVJxm4r6horvou8tMsvNq7QpM

###
POST  http://localhost:5001/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmdoaWEiLCJpYXQiOjE2NzM0MTY4OTksImV4cCI6MTY3MzQyMjg5OX0.HHTiVulWZPAE0Ol9vntVJxm4r6horvou8tMsvNq7QpM

{
    "title": "string",
    "description":"string",
    "image": "string",
    "benifit": "string",
    "field": "English"
}

###
GET  http://localhost:5001/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmdoaWEiLCJpYXQiOjE2NzM0MTY4OTksImV4cCI6MTY3MzQyMjg5OX0.HHTiVulWZPAE0Ol9vntVJxm4r6horvou8tMsvNq7QpM

###
GET  http://localhost:5001/courses/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmdoaWEiLCJpYXQiOjE2NzM0MTY4OTksImV4cCI6MTY3MzQyMjg5OX0.HHTiVulWZPAE0Ol9vntVJxm4r6horvou8tMsvNq7QpM


###
PATCH   http://localhost:5001/courses/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmdoaWEiLCJpYXQiOjE2NzM0MTY4OTksImV4cCI6MTY3MzQyMjg5OX0.HHTiVulWZPAE0Ol9vntVJxm4r6horvou8tMsvNq7QpM

{
    "title": "string1",
    "description": "string1",
    "image": "string1",
    "benifit": "string1",
    "field": "string1"
}

###
DELETE   http://localhost:5001/courses?id=4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmdoaWEiLCJpYXQiOjE2NzM0MTY4OTksImV4cCI6MTY3MzQyMjg5OX0.HHTiVulWZPAE0Ol9vntVJxm4r6horvou8tMsvNq7QpM
