POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"adsa@gmail.com",
    "password":"147258369",
    "firstName":"nghia",
    "lastname":"nghia"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"adsa@gmail.com",
    "password":"147258369"
}
